# test config file example

title = "Spotify-Jukebox Test Config File"

# uncategorized options
max_users = 1000

[spotify]
client_id = "d36aba7793284dd2a3544835c0be73a6"
client_secret = "573dfc80b40c487282fd6df42f742366"
redirect_url = "http://127.0.0.1:8080/redirect"
state = "state"
open_browser = true

[server]
port = 8080
frontend_base_url = "http://localhost:3000"

[database]
db_user = "root"
db_password = "root"
db_host = "127.0.0.1"
db_port = 53272
db_name = "spotify-jukebox-test"
user_collection_name = "users"
session_collection_name = "sessions"
