# test config file example

title = "Encore-Backend Config File"

# uncategorized options
max_users = 1000

# configuration options for the server's session garbage collector
[garbagecoll]
# 48h = 172800s per default
session_expiration_s = 172800
# 1h = 3600s per default
cleaning_interval_s = 3600

[spotify]
redirect_url = "http://localhost:3000/callback"

[server]
frontend_base_url = "http://localhost:3000"

[database]
db_port = 27017
db_name = "spotify-jukebox"
user_collection_name = "users"
session_collection_name = "sessions"
