# test config file example

title = "Spotify-Jukebox Config File"

# uncategorized options
max_users = 1000

[spotify]
redirect_url = "https://api.encore-fm.com/callback"

[server]
frontend_base_url = "https://encore-fm.com"

[database]
db_port = 27017
db_name = "spotify-jukebox"
user_collection_name = "users"
session_collection_name = "sessions"
