# config file example

title = "Spotify-Jukebox Config File"

# uncategorized options
max_users = 1000

[admin]
username = "admin"
password = "password"

[spotify]
client_id = "id"
client_secret = "secret"
redirect_url = "redirect.url"
state = "state"

[server]
port = 8080
frontend_base_url = "http://localhost:3000"

[database]
db_host = "127.0.0.1"
db_port = 27017
db_name = "spotify-jukebox"
user_collection_name = "users"
song_collection_name = "songs"



